name: HTML Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-validate:
    uses: ./.github/workflows/reusable-html-check.yml
    with:
      html-path: index.html
