name: Secret Test

on:
  push:
    branches: [main]

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Secretを使う
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Secret is set: $MY_SECRET"
